### ISSUE TITLE
DONE keyword is green in overview, red in agenda

### ISSUE THREAD

**Issue by wilbowma** [MobileOrg/mobileorg#80] opened 2016-09-04 18:41 UTC
Without some notification system, or filtering by scheduled/due date, looking at which tasks are still not done in my agenda view is the only workflow I've found for "what still needs to be done today".

But DONE items still appear red in the agenda view, making this more difficult than it needs to be, especially considering they appear green in the outline view.

**Comment by wilbowma** [comment] 2016-09-30 23:52
This seems to only be true of repeating event.

**Comment by webframp** [comment] 2016-12-19 03:50
Sounds like a reasonable bug, can you provide some steps to reproduce this scenario? Thanks

**Comment by webframp** [comment] 2016-12-20 03:48
In current testing versions these keywords have no color. Will look into this before final release

![mobileorg-testing-image](https://cloud.githubusercontent.com/assets/774378/21337659/0a427642-c624-11e6-897d-160231a09942.png)

**Comment by mgmart** [comment] 2016-12-20 09:45
That's probably caused by using the default keywords. If I customise the keywords then all the keywords are coloured. Could be fixed by the fix concerning #86

**Comment by webframp** [comment] 2016-12-20 15:46
Fixes in #88 didn't impact this one for me, but that's ok for now

**Comment by wilbowma** [comment] 2016-12-20 17:31
I'm not exactly sure how to reproduce this. I get seemingly random behaviors:
- sometimes, I can't mark things as "DONE", only "DONEARCHIVE"
- sometimes, I can and when I do, the "DONE" tag appears in green
- sometimes, I can and when I do the "DONE" tag appears in red
- sometimes, the "TODO" and "DONE" tags appear without any color

I've noticed that, contrary to my earlier comment, this doesn't just happen with recurring events.

I just looked at my weekly Agenda view, and all the tags were without color. Then, I synced (the agenda was from 2 days ago), and now everything is red, I can mark things as "DONE", but they stay red.

**Comment by mgmart** [comment] 2016-12-20 17:42
I assume you're using the AppStore version of MobileOrg. We've changed a lot in the new version which is available only from GutHub at the moment. Might it be possible for you to give the new version a try? As it works with individual Dropbox API keys you could do the tests with separate test data and keep your productive data safe. I tried the tasks you have described with my data and everything worked as expected. But additional tests with different data are much appreciated.

**Comment by webframp** [comment] 2016-12-21 01:31
I recreated my org files using some archive files I had, keyword colors are preserved. I think my issue was just in how I created the test files before. Considering this one closed

**Comment by mgmart** [comment] 2016-12-21 11:29
What makes me wonder is that I got the correct colouring by using the [testfiles you provided](https://github.com/MobileOrg/mobileorg/files/662678/index_out_of_range_data.zip)

I fear there is still something not right.

**Comment by wilbowma** [comment] 2016-12-22 15:48
@mgmart You're right that I'm using the version from the AppStore, so perhaps this issue has been fixed. I could give the GitHub version a try, but I don't know how to install apps from not-the-AppStore.

**Comment by mgmart** [comment] 2016-12-22 19:30
@wilbowma without Xcode experience it could be a difficult task to build and install the app. We should assume that the issue has been fixed meanwhile as all tests indicate as such.

**Comment by thaaophz** [comment] 2017-01-04 20:05
> But DONE items still appear red in the agenda view, making this more difficult than it needs to be, especially considering they appear green in the outline view.

Same problem here building the app from ff1978705d7f3f4b94c7f8555105f5e9ac27275a.

Furthermore the color of an entry does not change if I use agenda view to mark it as DONE.

**Comment by mgmart** [comment] 2017-01-05 07:57
> Furthermore the color of an entry does not change if I use agenda view to mark it as DONE.

Could reproduce that.

**Comment by thaaophz** [comment] 2017-01-05 08:27
> Furthermore the color of an entry does not change if I use agenda view to mark it as DONE.
> Could reproduce that.
#114 does not fix it for me.

**Comment by mgmart** [comment] 2017-01-05 08:42
My tests so far:
I start from `Agenda Views... -> ToDo: All...`
From there I switch back and forth between all possible stages and get the right color every time.
No difference wether I use `Flag this node` or by switching `Todo State`

Could you provide the  steps you made?
If you have a different result with my steps it could be useful if you could provide some test data.

**Closed** 2017-01-06 14:27 UTC
Labels: bug
