### ISSUE TITLE
mobileorg seems to have bug sometime when syncing from iPhone

### ISSUE THREAD

**Issue by clfest** [MobileOrg/mobileorg#191] opened 2017-05-13 08:04 UTC
I use Dropbox. It seems when I sync from the iPhone on a topic that MobileOrg has written an ID number on, the text reverts back to what the dropbox document has, the 'old' one. The mobileorg.org on dropbox seems to have the appropriate editing commands in it, so that when I pull it from my emacs and push it and sync my iPhone with it, it is correct. The problem is making more than one editing command one such a location and syncing in between, which I would expect, is broken.

It seems like the appropriate action is for the iPhone to take the 'new' version, rather than going back to the
'old' one.

**Comment by mgmart** [comment] 2017-05-13 08:26
Could this be related to #181?

**Comment by mgmart** [comment] 2017-05-13 09:37
@clfest, do you use `org-mobile-force-id-on-agenda-items`?

**Comment by clfest** [comment] 2017-05-14 09:29
I'm a little rusty on lisp-type syntax, but if you mean is
org-mobile-force-id-on-agenda-items mentioned in my .emacs file, no it is
not.
NB: the above phenomenon occurs with a regular .org file, NOT with an
agenda file.

**Comment by mgmart** [comment] 2017-05-14 10:11
Tried to reproduce this issue:

- Edit the body text of an item which has a mobile-org-id
- Sync with dropbox
- Add more text to body
- Sync with dropbox
- Add more text
- Sync with dropbox

Outcome was as expected.

Could you try to reproduce this with the testdata available at https://github.com/MobileOrg/mobileorg/tree/develop/MobileOrgTests/Resources ?

**Comment by mgmart** [comment] 2017-05-14 10:38
MobileOrg iOS TestData/And one more thing/learn a new language

is the item which is used for my reproduction attempt

**Comment by mgmart** [comment] 2017-06-19 06:18
Could be related to #97

**Comment by clfest** [comment] 2017-06-24 19:27
Before I try to reproduce said defect, what evidence would you require?
Since the observed bug seems only to occur in the communication between the
iPhone's app and the Dropbox's data,
and I don't really have any way of getting the iPhone's data out directly,
what I anticipate is that the iPhone's data will revert back to the
previous one after I sync, which will mirror the data in
my computer, but that the Apps/MoblieOrg/mobileorg.org will show my recent
edits. Would a copy of said mobileorg.org suffice, with a written
description of what I see on my iPhone?

**Comment by mgmart** [comment] 2017-06-25 06:59
> Before I try to reproduce said defect, what evidence would you require?

[I was not able to reproduce the issue with the testdata](https://github.com/MobileOrg/mobileorg/issues/191#issuecomment-301302752).

If you are also not able to reproduce it with the testdata, we could change the testdata in the next step. To make it look more like the org-files you have. Maybe we could then find the cause of the issue.

**Comment by webframp** [comment] 2017-08-01 12:43
Hey there @clfest let us know if you are still experiencing this with the latest version. Thanks

**Comment by mgmart** [comment] 2017-08-13 07:26
Closing the ticket because of no feedback. Could be re-opened if necessary.

**Closed by mgmart** 2017-08-13 07:26 UTC
Labels: org-mode

**Comment by clfest** [comment] 2017-08-14 08:21
No, I am not experiencing the original problem with the new version.  I am
experiencing some irregularities with the TODO->DONE feature,
but I will enter it as a new bug when I have the time to make a more
specific description.
