### ISSUE TITLE
MobileOrg crashes all the time

### ISSUE THREAD

**Issue by clfest** [MobileOrg/mobileorg#196] opened 2017-06-18 07:31 UTC
My MobileOrg app on my iPhone gets stuck in a mode where it refuses to open. That is when 'stuck' you can open it, and then it lasts for about a second, and crashes. I've tried powering down and then powering up my iPhone, but it doesn't seem to help. My only choice is to reinstall the app, but that loses the unsynced data in the iPhone's app. This and the previous bug I reported (when syncing, somtimes the item goes back to the original), makes this application risky for storing data. Furthermore, the last time the interval between entering 'stuck'  modes was only about half a day.

**Comment by mgmart** [comment] 2017-06-19 05:18
> and then it lasts for about a second, and crashes

That sounds like an issue with Core Data. If you are sharing [sharing crash data with app developers](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AnalyzingCrashReports/AnalyzingCrashReports.html#//apple_ref/doc/uid/TP40012582-CH21-SW2), @webframp would be able to see your crash log.

> This and the previous bug I reported

You are referencing #191, which we were not able to reproduce. Could you please try to reproduce with the testdata provided?

Furthermore it would be helpful if we would have as much information about your setup as possible.

- Are you using encryption?
- What's your MobileOrg version?
- What's the device(s) you are using?
- Which iOS version is installed on device(s)?

**Comment by clfest** [comment] 2017-06-19 17:45
My system seems to be set up a little different from what is described in the page that you referenced. In particular under Privacy there is no 'Diagnostics & Usage' tab. However there is an 'Analytics' tab, under which I've got 'Share iPhone Analytics', 'Share with App Developers' and 'Share iCloud Analytics' turned on.

I am not using encryption
I believe I am using the latest version of MobileOrg (1.7.2)
My device is iPhone 6
iOS 10.3.2
I am using dropbox

**Comment by mgmart** [comment] 2017-06-20 05:43
> 'Share with App Developers' and 'Share iCloud Analytics' turned on.

That would be sufficient, @webframp should be able to access the crash-log.

Would be cool if you could try to reproduce #191 with the test-data  provided, in the meantime.

**Comment by mgmart** [comment] 2017-08-13 07:26
Closing the ticket because of no feedback. Could be re-opened if necessary.

**Closed by mgmart** 2017-08-13 07:26 UTC
Labels: bug

**Comment by clfest** [comment] 2017-08-14 08:23
Having downloaded the updated version, I will see if the same bug manifests
itself. Thank You.
