### ISSUE TITLE
new error when syncing

### ISSUE THREAD

**Issue by clfest** [MobileOrg/mobileorg#284] opened 2021-10-15 05:48 UTC
There's a new error when attempting to sync from my iPhone 6. I use DropBox and the image is attached. My guess is they've
changed something about DropBox.
![IMG_1978](https://user-images.githubusercontent.com/28668846/137438687-8b0eae62-988d-4d47-a294-af5ef36f87df.PNG)

**Comment by johnmw** [comment] 2021-10-19 07:52
I have the same issue. Glad its not just me - I thought it might be some data corruption preventing the sync.

I am also on iOS using dropbox sync. have tried updating mobileorg, dropbox, and relinking.

Putting the error text in, in case someone else is searching for it.

```
Error syncing changes
An error was encountered while attempting to fetch mobileorg.org from the server. The error was:

[request-id
... API route error = {
".tag" = path;
path = {
".tag" = "restricted_content"; 
};
}
```

**Comment by webframp** [comment] 2021-10-19 22:31
Thanks for reporting this. I am using the latest iOS 15 release and the current App Store version and haven't been able to reproduce this myself yet. 

I'll keep investigating. If you have any more specific info to add for reproducing I'll give it a try.

**Comment by clfest** [comment] 2021-10-20 00:08
I don't think the iPhone 6 goes up that far. I keep mine up and it's 12.5.5. The good thing is this seems to happen consistently. I have no idea what the 'conversation' that takes places when you press the sync button is between Dropbox and your iPhone.

**Comment by gvol** [comment] 2021-10-26 06:47
I'm also seeing this.  Willing to do any sort of debugging that I can.   iOS 14.7.1 on an iPhone 7 Plus.

**Comment by gvol** [comment] 2021-11-08 23:12
It went away.  Everything is now working.  I don't recall doing anything special.  Perhaps it was a problem on Dropbox's side??

**Comment by clfest** [comment] 2021-11-10 05:10
Yes, went away for me too. As you were.

**Comment by webframp** [comment] 2021-11-10 14:16
glad to hear that at least @gvol and @clfest 

I tried a few times to recreate it and couldn't reproduce in the simulator, I also wonder if it was an issue on the Dropbox side.

will close this one for now but definitely report if it pops up again

**Closed as completed by webframp** 2021-11-10 14:16 UTC
